version: 2
jobs:
  compile:
    docker:
      - image: mhmmdfas/mydockerimage:latest
    steps:
      - checkout
      - run: git clone --quiet -j32 https://github.com/fadlyas07/build-scripts --depth=1
      - run: bash build-scripts/rolex.sh
  compiletoo:
    docker:
      - image: mhmmdfas/mydockerimage:latest
    steps:
      - checkout
      - run: git clone --quiet -j32 https://github.com/fadlyas07/build-scripts --depth=1
      - run: bash build-scripts/riva.sh
workflows:
  version: 2
  cooking:
    jobs:
      - compile
      - compiletoo
