version: 2
jobs:
  sendinfo:
    docker:
      - image: fadlyas/kernel_dockerfile:latest
    steps:
      - checkout
      - run: bash /root/toolchain/scripts/eas-rolex.sh
  compile:
    docker:
      - image: fadlyas/kernel_dockerfile:latest
    steps:
      - checkout
      - run: bash /root/toolchain/scripts/eas-riva.sh
workflows:
  version: 2
  cooking:
    jobs:
      - sendinfo
      - compile
